### PR TITLE
Bump to latest JSHint

### PR DESCRIPTION
**Pull request by pivotal-casebook**
Bumps to latest JSHint version.

### CODE REVIEW

**Comment by pivotal-casebook** [comment]
er, that should read latest _jshint_. shoot.

**Comment by mackuba** [comment]
The JSHint branch is a work in progress, and it's paused currently because the author said he was going to redesign the options completely (https://github.com/jshint/jshint/issues/166) - if he is indeed going to do it then I'd have to redesign everything here anyway, so I'd rather wait until he does...

I can merge this in if this matters to you, but as I said, this branch is more like a hidden feature for now.

**Comment by grosser** [comment]
jshint 2.0 is out, now what ? :)

**Comment by mackuba** [comment]
Thanks for info, I'll check it out :)

**Pull request closed without merging**
