### PR TITLE
Added basic JSHint support

### PR DESCRIPTION
**Pull request by shajith**
Would like to know if you'd like to roll this into jslint_on_rails.

### CODE REVIEW

**Comment by mackuba** [comment]
Hi,

so, first, you're right that there isn't much activity in my repo. There are a few reasons for this:
- I'm kind of busy right now
- there isn't much to add in a project like this, except periodically updating the JSLint core to the latest version and fixing bugs sometimes, which I've done a few times
- last time I tried to update JSLint, I looked in Crockford's repo, I saw that there were some major changes and I decided that I didn't like the direction in which this was going. I also saw JSHint later, so I thought I'd update the project to use JSHint instead of JSLint when I find some time and release this as gem version 1.1. I just didn't have time to do this yet, but basically my plans were to do what you did.

So I'm not planning to maintain a version of the gem/plugin that uses the original JSLint. The question is which way we should go now - should I let you work on your fork with a different name and release this as a different gem, and add info on mine that I recommend switching to yours; or if I should merge your changes into my repo/gem and keep the old name; or maybe let you develop this in your repo and push to my gem... I'm not sure what to tell you right now, let me think about this and get back to you.

And there's also the question of how https://github.com/Bgouveia/jshint_on_rails fits into all of this...

**Comment by shajith** [comment]
Hey,
I'm sorry, I wasn't implying that there isn't much activity on _your_ repository, I was talking about the jshint_on_rails project you mentioned. Not to slight that developer, mind you, just by way of explanation for why I didn't see that. 

I'm cool with which ever way you wanna go with this. I'll be glad to send you a pull request if you ever want to use this code, or if you want to change it or whatever. No pressure or anything! :) We're going to start using jshint over at the dayjob, I'll work on improving this when that happens.

Cheers!
Shajith

**Comment by mackuba** [comment]
Hi,

I've reviewed all the forks, and I like your approach the most (option to still run old jslint - I haven't thought of that - and keeping the old module/file names). I'll be merging this in soon. (Funny how https://github.com/liquid/jshint_on_rails and https://github.com/Bgouveia/jshint_on_rails have done exactly the same work completely independently and released that as two independent gems ;)

I've also sent a [patch to JSHint](https://github.com/jshint/jshint/commit/1f2cf9a32f4ab9081b6dd0e03d2072e030dd5643) to include my lastsemic option in the mainstream version (the other two options should be covered by those already in JSHint).

**Comment by mackuba** [comment]
Mostly finished: https://github.com/psionides/jslint_on_rails/tree/jshint (readme not updated yet).

I'll wait a bit with a release though, because there's some confusion about changes in options. Crockford made a commit last week that changes the meaning of several boolean options to the opposite, and the author of JSHint is considering using "ignore"/"warn" strings as option values instead. I might have to revert some of what I wrote this week...

**Pull request closed without merging**
